name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Docker image
      run: |
        docker build -t myapp:${{ github.sha }} .
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push Docker image
      run: |
        docker tag myapp:${{ github.sha }} myusername/myapp:latest
        docker push myusername/myapp:latest
    - name: Deploy Docker container
      run: |
        docker run -d --name myapp_container -p 80:80 myusername/myapp:latest
